debug_mode: "debug"
time_location: "Asia/Chongqing"
salt: "dga32gw4wfw4e454fdga34"
sign-key: "my_sign_key"

http:
  addr: ":8200"
  read_timeout: 10
  write_timeout: 10
  max_header_bytes: 20

swagger:
  title: "go_gateway swagger API"
  desc: "This is a sample server celler server."
  host: "192.168.10.213:8200"
  base_path: ""

mysql:
  host: "localhost"
  port: 3306
  name: "gateway"
  user: "root"
  password: "123456"

proxy:
  http:
    addr: ":8300"
    read_timeout: 10
    write_timeout: 10
    max_header_bytes: 20

  https:
    addr: ":8443"
    read_timeout: 10
    write_timeout: 10
    max_header_bytes: 20
    cert_crt_file: "D:/OpenSourceCode/proxy/conf/server.crt"
    cert_key_file: "D:/OpenSourceCode/proxy/conf/server.key"

web:
  url: "/ifc"
  path: "D:/OpenSourceCode/gateway-admin/dist"
  addr: ":8400"
  read_timeout: 10
  write_timeout: 10
  max_header_bytes: 20